<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="CommonTools.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OllamaSharp" Version="5.4.25" />
    <PackageReference Include="Serilog" Version="4.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aiyara.Harness.Models\Aiyara.Harness.Models.csproj" />
  </ItemGroup>
</Project>
