<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="CommonTools.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ModelContextProtocol.Core" />
    <PackageReference Include="OllamaSharp" />
    <PackageReference Include="Serilog" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aiyara.Harness.Models\Aiyara.Harness.Models.csproj" />
  </ItemGroup>
</Project>
