using Aiyara.Harness.Models.Config;

using OllamaSharp.Models.Chat;

namespace Aiyara.Harness.Tools;

/// <summary>
/// A tool for saving a Base64-encoded image (e.g. one generated by the model) to a file.
/// </summary>
public class SaveImageTool : BaseTool
{
    public SaveImageTool()
    {
        Type = "function";
        Function = new Function
        {
            Name = "save_image",
            Description = "Save a Base64-encoded image to a file, creating any missing parent directories.",
            Parameters = new Parameters
            {
                Properties = new Dictionary<string, Property>
                {
                    {
                        "file_path",
                        new Property { Type = "string", Description = "The path to save the image file to." }
                    },
                    {
                        "base64_data",
                        new Property
                        {
                            Type = "string",
                            Description =
                                "The Base64-encoded image data. A 'data:image/...;base64,' prefix, if present, is stripped automatically."
                        }
                    }
                },
                Required = new List<string> { "file_path", "base64_data" }
            }
        };
    }

    /// <summary>
    /// Invokes the method to save a Base64-encoded image to a file.
    /// </summary>
    /// <param name="args"></param>
    /// <returns></returns>
    protected override object? Execute(IDictionary<string, object?>? args) =>
        SaveImage(
            args?.TryGetValue("file_path", out var filePath) == true ? (string?)filePath : null,
            args?.TryGetValue("base64_data", out var base64Data) == true ? (string?)base64Data : null);

    /// <summary>
    /// Decodes Base64 image data and writes it to a file, returning a confirmation message so the model
    /// knows the save succeeded.
    /// </summary>
    /// <param name="filePath"></param>
    /// <param name="base64Data"></param>
    /// <returns></returns>
    /// <exception cref="ArgumentException"></exception>
    /// <exception cref="UnauthorizedAccessException"></exception>
    public static string SaveImage(string? filePath, string? base64Data)
    {
        if (string.IsNullOrEmpty(filePath))
        {
            throw new ArgumentException("File path cannot be null or empty.", nameof(filePath));
        }

        if (string.IsNullOrEmpty(base64Data))
        {
            throw new ArgumentException("Base64 image data cannot be null or empty.", nameof(base64Data));
        }

        var commaIndex = base64Data.IndexOf(',');
        var payload = base64Data.StartsWith("data:", StringComparison.OrdinalIgnoreCase) && commaIndex >= 0
            ? base64Data[(commaIndex + 1)..]
            : base64Data;

        byte[] bytes;
        try
        {
            bytes = Convert.FromBase64String(payload);
        }
        catch (FormatException ex)
        {
            throw new ArgumentException("Base64 image data is not valid Base64.", nameof(base64Data), ex);
        }

        var resolvedPath = Workspace.ResolvePath(filePath);
        var overwriting = File.Exists(resolvedPath);

        var approved = ActionConsent.Confirm("save_image",
            "image write",
            $"{(overwriting ? "overwrite" : "create")} {resolvedPath}");

        if (!approved)
        {
            throw new UnauthorizedAccessException($"Saving to '{filePath}' was not approved.");
        }

        var directory = Path.GetDirectoryName(resolvedPath);
        if (!string.IsNullOrEmpty(directory))
        {
            Directory.CreateDirectory(directory);
        }

        File.WriteAllBytes(resolvedPath, bytes);

        return $"Saved {bytes.Length} bytes to '{filePath}'.";
    }
}
